# SEMESTER THREE : Data Structures

## Polynomials
**dont use the given programs as they are for reference only**

### Algorithm to add two Polynomials.

1. create a sum array `sum[]` for size to maximum of `m` and `n`
2. copy `A[]` to `sum[]`.
3. Traverse array `B[]` and do following for every element `B[i]`
   - `sum[i] = sum[i] + B[i]`
4. Return `sum[]`.

```cpp
#include <iostream>
#include<algorithm>

using namespace std;
void logPolynomial(int polynomial[],int degree){
    for(int i = degree;i>=0;i--){
        if(polynomial[i]){
            if (i==0){
                cout<<polynomial[i];
            } else {
                cout<<polynomial[i]<<"x^"<<i<<" + ";
            }
        }
    }
}
int main() {
    int degree;
    cout << "Enter the degree of the first polynomial equation: ";
    cin >> degree;
    int *polynomial = new int[degree+1];
    for(int i=0;i<=degree;i++){
        cout << "Enter the coefficient of X^"<<i<<" : ";
        cin>>polynomial[i];
    }

    int degree2;
    cout << "Enter the degree of the second polynomial equation: ";
    cin >> degree2;
    int *polynomial2 = new int[degree2+1];
    for(int i=0;i<=degree2;i++){
        cout << "Enter the coefficient of X^"<<i<<" : ";
        cin>>polynomial2[i];
    }

    cout << "a = ";
    logPolynomial(polynomial,degree);
    cout<<endl;

    cout << "b = ";
    logPolynomial(polynomial2,degree2);
    cout<<endl;

    int maxlen = max(degree,degree2);
    int *sum = new int [maxlen];
    for(int i=0;i<=degree;i++){
        sum[i] = polynomial[i]; 
    }
    for(int i=0;i<=degree2;i++){
        sum[i] = sum[i] + polynomial2[i];
    }

    cout << "sum = ";
    logPolynomial(sum,maxlen);
    cout<<endl;
    return 0;
}
```

### Algorithm to multiply two Polynomials.

**multiply(A[0..m-1],B[0..n-1])**

1. create a product array `prod[]` of size `m+n-1`
2. initalize all entries in `prod[]` as 0.
3. Traverse array `A[]` and do follow for every element `A[i]`
   1. Traverse array `B[]` and do following for every element `B[j]`
      - `prod[i+j] = prod[i+j] + A[i] * B[j]`
4. Return `prod[]`.

```cpp
#include <iostream>

using namespace std;
void logPolynomial(int polynomial[],int degree){
    for(int i = degree;i>=0;i--){
        if(polynomial[i]){
            if (i==0){
                cout<<polynomial[i];
            } else {
                cout<<polynomial[i]<<"x^"<<i<<" + ";
            }
        }
    }
}

int main() {
    int degree;
    cout << "Enter the degree of the first polynomial equation: ";
    cin >> degree;
    int *polynomial = new int[degree+1];
    for(int i=0;i<=degree;i++){
        cout << "Enter the coefficient of X^"<<i<<" : ";
        cin>>polynomial[i];
    }

    int degree2;
    cout << "Enter the degree of the second polynomial equation: ";
    cin >> degree2;
    int *polynomial2 = new int[degree2+1];
    for(int i=0;i<=degree2;i++){
        cout << "Enter the coefficient of X^"<<i<<" : ";
        cin>>polynomial2[i];
    }

    cout << "a = ";
    logPolynomial(polynomial,degree);
    cout<<endl;

    cout << "b = ";
    logPolynomial(polynomial2,degree2);
    cout<<endl;

    int *prod = new int[degree+degree2+1];
     
    for(int i=0;i<degree+degree2+1;i++){
        prod[i] = 0;
    }
    for(int i=0;i<=degree;i++){
        for(int j=0;j<=degree2;j++){
            prod[i+j] = prod[i+j] + polynomial[i] * polynomial2[j];
        }
    }


    cout << "product = ";
    logPolynomial(prod,degree+degree2+1);
    cout<<endl;
    return 0;

}
```


## Algorithms

### Linear Search

1. initalize `pos = -1`
2. initalize `i = 1`
3. Repeat step 4 `while i<=n`
    4. `if(A[i] = val )`
       - set `pos = i`
       - print `pos`
       - go to step 6
       - [End of if]
       - set `i = i + 1`
    - [End of loop]
5. `if(pos= -1)`
   - print *value is not present in array*
6. exit

```cpp
#include <iostream>
using namespace std;

void logArray(int array[],int n){
    for (int i = 0; i < n; i++){
        cout<<"| "<<array[i] <<" "; 
    }
    cout<<endl;
}

int main(int argc, char *argv[]){

    // array size and creation
    int size;
    cout << "Enter the Capacity of Array : ";
    cin >> size;
    int *arr = new int[size];

    // pre insert some values
    int len;
    cout << "Enter Number of elements to pre-insert: ";
    cin >> len;

    if(!len){
        cout << "Plese enter a valid number of elements" << endl;
        return -1;
    } 
    cout << "Enter "<< len <<" elements : " << endl;
    for (int i = 0; i < len; i++){
        cin>>arr[i]; 
    } 
    cout << "Elements : "<<endl;
    logArray(arr,size);

    int searchNum; 
    cout << "Enter a number to search: ";
    cin >> searchNum;

    int flag = 0;
    for (int i = 0; i < len; i++) {
        if(arr[i] == searchNum){
            flag = 1;
            cout << searchNum << " found at position " << i+1 << endl;
            break;
        }
    }
    if(!flag){
        cout << "element not found" << endl;
    }
    return 0;

}
```

### Binary Search

1. set `beg=lower_bound,end=upper_bound,pos=-1`
2. Repat steps 3 & 4 while `beg <= end`
3. set `mid = [beg+end/2]`
4. `if(A[mid] = val)`
   - set `pos=mid`
   - print `pos`
   - go to step 6
   1. `else if(A[mid] > val)`
      - set `end = mid -1`
   2. `else`
      - set `beg = mid + 1`
   - [End of if]  
   - [End of loop]  
5. if `pos=-1`
   - print *value is not present in the array*
6. exit

```cpp

```


